services:
  nest-app:
    build: .
    container_name: nest-app
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
    env_file:
      - .env
    depends_on:
      - mongo
    networks:
      - tictag-backend-network
    volumes:
      - ./uploads:/usr/src/app/uploads

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - ./data/db:/data/db
    networks:
      - tictag-backend-network

networks:
  tictag-backend-network:
    driver: bridge